### ISSUE TITLE
App crashes if you fail to fill in a required field creating a note

### ISSUE THREAD

**Issue by jonwest** [orditeck/calepin-frontend#3]
If I click on "Create Note", and fail to fill in any fields, and hit save, the app crashes.

```
Uncaught (in promise) Error: Request failed with status code 422
    at e.exports (createError.js:16)
    at e.exports (settle.js:18)
    at XMLHttpRequest.f.(anonymous function) (https://app.calepin.io/static/js/main.e05ffbf1.js:1:287962)
```

**Comment by jonwest** [comment]
This is also the case if you just miss a single field (language, for example).

**Comment by orditeck** [comment]
Does it pop an alert?

![](https://i.imgur.com/biRj7Mf.png)

Ah, just saw that the loading stays there forever after the alert. Must be what you're talking about?

**Comment by jonwest** [comment]
Yeah!  Sorry, should've been more specific.  Basically once you clear the alert, the loading wheels continue to spin and you need to click another link to get back to the app rather than have it dump you back to the note screen.

**Comment by orditeck** [comment]
Thanks for reporting this bug, I'll fix it this evening.

**Comment by orditeck** [comment]
Fixed, sorry about the delay.
